name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          PROJECTS=(mscape synthscape openmgs pathsafe)
          for p in ${PROJECTS}
          do
            # Uploader specifications
            python3 metadata/json2md.py -d 2 uploader metadata/${p}.json >> docs/${p}.md
            # Analysis specifications
            python3 metadata/json2md.py -d 2 analysis metadata/${p}-analysis.json >> docs/${p}-analysis.md
            # Template CSVs
            python3 metadata/json2md.py -d 2 template metadata/${p}.json > docs/${p}-template.csv
          done
          wget https://raw.githubusercontent.com/CLIMB-TRE/onyx-client/master/README.md -O docs/onyx_client_installation_guide.md
          # pip install 'onyx @ git+https://github.com/CLIMB-TRE/onyx-client@0b791a8237e0418aa42a2e0f98bac587d7afb95a'
          pip install climb-onyx-client
          pip install 'varys @ git+https://github.com/CLIMB-TRE/varys@ed2356a9d8de27cee05622710ad2fb23408c1e40'
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-macros-plugin
          pip install mkdocs-with-pdf
          pip install mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
