name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          # Uploader specifications
          python3 metadata/json2md.py -d 2 uploader metadata/mscape.json >> docs/mscape.md
          python3 metadata/json2md.py -d 2 uploader metadata/synthscape.json >> docs/synthscape.md
          python3 metadata/json2md.py -d 2 uploader metadata/openmgs.json >> docs/openmgs.md
          python3 metadata/json2md.py -d 2 uploader metadata/pathsafe.json  >> docs/pathsafe.md
          # Analysis specifications
          python3 metadata/json2md.py -d 2 analysis metadata/mscape-analysis.json >> docs/mscape-analysis.md
          python3 metadata/json2md.py -d 2 analysis metadata/synthscape-analysis.json >> docs/synthscape-analysis.md
          python3 metadata/json2md.py -d 2 analysis metadata/openmgs-analysis.json >> docs/openmgs-analysis.md
          python3 metadata/json2md.py -d 2 analysis metadata/pathsafe-analysis.json  >> docs/pathsafe-analysis.md
          # Template CSVs
          python3 metadata/json2md.py -d 2 template metadata/mscape.json > docs/mscape-template.csv
          python3 metadata/json2md.py -d 2 template metadata/synthscape.json > docs/synthscape-template.csv
          python3 metadata/json2md.py -d 2 template metadata/openmgs.json > docs/openmgs-template.csv
          python3 metadata/json2md.py -d 2 template metadata/pathsafe.json > docs/pathsafe-template.csv
          wget https://raw.githubusercontent.com/CLIMB-TRE/onyx-client/master/README.md -O docs/onyx_client_installation_guide.md
          # pip install 'onyx @ git+https://github.com/CLIMB-TRE/onyx-client@0b791a8237e0418aa42a2e0f98bac587d7afb95a'
          pip install climb-onyx-client
          pip install 'varys @ git+https://github.com/CLIMB-TRE/varys@ed2356a9d8de27cee05622710ad2fb23408c1e40'
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-macros-plugin
          pip install mkdocs-with-pdf
          pip install mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
